// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package promopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PromoServiceClient is the client API for PromoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromoServiceClient interface {
	Check(ctx context.Context, in *PromoServiceCheckRequest, opts ...grpc.CallOption) (*PromoServiceCheckResponse, error)
}

type promoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromoServiceClient(cc grpc.ClientConnInterface) PromoServiceClient {
	return &promoServiceClient{cc}
}

func (c *promoServiceClient) Check(ctx context.Context, in *PromoServiceCheckRequest, opts ...grpc.CallOption) (*PromoServiceCheckResponse, error) {
	out := new(PromoServiceCheckResponse)
	err := c.cc.Invoke(ctx, "/promo.v1.PromoService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromoServiceServer is the server API for PromoService service.
// All implementations must embed UnimplementedPromoServiceServer
// for forward compatibility
type PromoServiceServer interface {
	Check(context.Context, *PromoServiceCheckRequest) (*PromoServiceCheckResponse, error)
	mustEmbedUnimplementedPromoServiceServer()
}

// UnimplementedPromoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPromoServiceServer struct {
}

func (UnimplementedPromoServiceServer) Check(context.Context, *PromoServiceCheckRequest) (*PromoServiceCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedPromoServiceServer) mustEmbedUnimplementedPromoServiceServer() {}

// UnsafePromoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromoServiceServer will
// result in compilation errors.
type UnsafePromoServiceServer interface {
	mustEmbedUnimplementedPromoServiceServer()
}

func RegisterPromoServiceServer(s grpc.ServiceRegistrar, srv PromoServiceServer) {
	s.RegisterService(&PromoService_ServiceDesc, srv)
}

func _PromoService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoServiceCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promo.v1.PromoService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).Check(ctx, req.(*PromoServiceCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromoService_ServiceDesc is the grpc.ServiceDesc for PromoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promo.v1.PromoService",
	HandlerType: (*PromoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _PromoService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promo.proto",
}
