name: promo-readonly
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_MYSQL_HOST: 127.0.0.1
  DOCKER_MYSQL_DATABASE: readonly
  DOCKER_MYSQL_USERNAME: admin
  DOCKER_MYSQL_PASSWORD: 123456
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: readonly
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Tools
        run: make install-tools
      - name: Go Generate
        run: go generate ./...
      - name: Lint
        run: make lint
      - name: Set up integration test
        run: cp config.tmp.yml config_test.yml && sleep 20
      - name: Test
        run: make test
      - name: Test Race
        run: make test-race
      - name: Benchmark
        run: make benchmark
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
